spring:
  application:
    name : concurrency-control

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

  h2:
    console:
      enabled: true

logging:
  level:
    com.example.concurrency: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
#    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false
logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.orm.jpa: INFO
#    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO